// <auto-generated />
namespace JobM_NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SecondName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondName));
        
        string IMigrationMetadata.Id
        {
            get { return "202101181510291_SecondName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
